hmrc/awrs-frontend

app/connectors/AWRSConnector.scala

Updated logging

---

app/views/helpers/confirmationHelper.scala.html

[AWRS-1983] - replace DIV tags with SPANS within H1 in order to resolve read back in NVDA

[AWRS-1983] - replace DIV tags with SPANS within H1

---

app/services/EnrolService.scala
test/services/EnrolServiceTest.scala

Revert "revert knownfact code for Live release"

---

app/views/includes/awrs_main.scala.html
public/javascripts/details.polyfill.js

Implemented fix as suggested by gov.uk team to sort out DAC - Priority A - Compatibility issues.

implemented polyfill fix

---

conf/app.routes

Revert "amended app.routes - changed email verifiction from GETs to POSTs"

---

app/views/helpers/awrsAddressHelper.scala.html

[AWRS-2127] Bold address labels / Amend address label 1

[AWRS-2127] Bold address labels / Amend address label 1

---

app/views/helpers/confirmationHelper.scala.html
public/stylesheets/custom.css

[AWRS-2058] - Accessibility header issue

[AWRS-2058] - Accessibility header issue

---

app/views/helpers/awrsAnswerQuestionHelper.scala.html
public/javascripts/awrs.js
public/javascripts/details.polyfill.js
public/stylesheets/custom.css

[AWRS-1853] - DAC - Priority A - Compatibility

[AWRS-1853] - DAC - Priority A - Compatibility

---

app/views/helpers/awrsInputTypeRadioGroup.scala.html

Revert "added tab index for radio button tabbing chrome"

---

app/views/helpers/errorSummaryTemplate.scala.html

Revert "replaced H1 with H2 as DAC requested"

---

app/views/awrs_de_registration_confirm.scala.html

[AWRS-2123] - add missing comma

[AWRS-2123] - add missing comma

---

public/javascripts/awrs.js

[AWRS-2136] - add tabindex to #content for accessibility

[AWRS-2136] - add tabindex to #content for accessibility

---

project/FrontendBuild.scala

[AWRS-2075] - upgrade bootstrap dependency

[AWRS-2075] - upgrade bootstrap dependency

---

public/javascripts/awrs.js

[AWRS-2003] - Add JS solution for skip to main content.
Removed tabindex="-1" from #content

[AWRS-2003] - Add JS solution for skip to main content

---

app/views/helpers/awrsInputTypeText.scala.html
public/javascripts/awrs.js
public/stylesheets/custom.css

[AWRS-2146] - Wave Accessibility on Radio buttons & Checkboxes for Registration Service

[AWRS-2146] - Wave Accessibility on Radio buttons & Checkboxes for Registration Service

---

app/views/helpers/awrsUnSubmittedBanner.scala.html
conf/messages

Amended submit changes banner - removed submit changes link, and changed message wording.

AWRS-2155: Amend submit changes banner

---

app/services/JourneyConstants.scala
app/views/helpers/awrsProgressHelper.scala.html
conf/messages

[AWRS-2138] - Accessibility - Progress text not read out

[AWRS-2138] - Accessibility - Progress text not read out

---

app/views/helpers/confirmationHelper.scala.html

[AWRS-2058] - Accessibility header issues

[AWRS-2058] - Accessibility header issues

---

app/views/awrs_additional_premises.scala.html
app/views/awrs_business_contacts.scala.html
app/views/awrs_business_details.scala.html
app/views/awrs_business_directors.scala.html
app/views/awrs_business_registration_details.scala.html
app/views/awrs_group_member.scala.html
app/views/awrs_partner_member_details.scala.html
app/views/awrs_principal_place_of_business.scala.html
app/views/awrs_products.scala.html
app/views/awrs_supplier_addresses.scala.html
app/views/awrs_trading_activity.scala.html
app/views/helpers/awrsProgressHelper.scala.html
app/views/helpers/backLink.scala.html
app/views/view_application/subviews/subview_core.scala.html
app/views/view_application/subviews/subview_delete_confirmation.scala.html

[AWRS-2138] - Accessibility - Read out header followed by section

[AWRS-2138] - Accessibility - Read out header followed by section

---

app/views/awrs_additional_premises.scala.html
app/views/awrs_business_contacts.scala.html
app/views/awrs_business_details.scala.html
app/views/awrs_business_directors.scala.html
app/views/awrs_business_registration_details.scala.html
app/views/awrs_group_member.scala.html
app/views/awrs_partner_member_details.scala.html
app/views/awrs_principal_place_of_business.scala.html
app/views/awrs_products.scala.html
app/views/awrs_supplier_addresses.scala.html
app/views/awrs_trading_activity.scala.html
app/views/helpers/awrsProgressHelper.scala.html
app/views/helpers/backLink.scala.html
app/views/view_application/subviews/subview_core.scala.html
app/views/view_application/subviews/subview_delete_confirmation.scala.html
conf/messages
public/stylesheets/custom.css
test/views/AdditionalPremisesViewTest.scala
test/views/AdditionalSupplierViewTest.scala
test/views/BusinessContactsViewTest.scala
test/views/BusinessDetailsViewTest.scala
test/views/BusinessDirectorsViewTest.scala
test/views/BusinessPartnersViewTest.scala
test/views/BusinessRegistrationDetailsViewTest.scala
test/views/GroupMembersViewTest.scala
test/views/PlaceOfBusinessViewTest.scala
test/views/ProductsViewTest.scala
test/views/TradingActivityViewTest.scala

[AWRS-2138] - Fix progress sub-heading for VO

[AWRS-2138] - Fix progress sub-heading for VO

---

app/views/awrs_de_registration_confirm.scala.html
app/views/awrs_withdrawal_confirmation.scala.html
app/views/helpers/InputTypeRadioGroupParams.scala
app/views/helpers/awrsInputTypeRadioGroup.scala.html
app/views/helpers/awrsWarningHelper.scala.html

[AWRS-2150] - Fix point 5ii for VO Accessibility

[AWRS-2150] - Fix point 5ii for VO Accessibility

---

app/views/helpers/backLink.scala.html
conf/messages

[AWRS-2138] - amend aira prefix for 'Section' to 'This section is'
Remove visually hidden comma from  Back link.

[AWRS-2138] - amend aira prefix for 'Section' to 'This section is'

---

app/views/awrs_business_details.scala.html
app/views/awrs_business_directors.scala.html
app/views/helpers/awrsNewBusinessHelpTextHelper.scala.html

[AWRS-2147] - NVDA Accessibility on Radio button & Check Boxes on Registration Service

[AWRS-2147] - NVDA Accessibility on Radio button & Check Boxes on Registration Service

---

app/views/awrs_business_details.scala.html
app/views/helpers/awrsInputTypeRadioGroup.scala.html

[AWRS-2147] - fix aria-describedby on radioGroups

[AWRS-2147] - fix aria-describedby on radioGroups

---

app/views/helpers/awrsInputTypeRadioGroup.scala.html

[AWRS-2147] - fix aria describedby within radiogroup for option No

[AWRS-2147] - fix aria describedby within radiogroup for option No

---

app/views/awrs_de_registration_confirm.scala.html
app/views/awrs_withdrawal_confirmation.scala.html

Fix to read question and hint text for yes radio option on dereg and cancel confirmation pages

[AWRS-2150] - Fix to read question and hint text for yes radio option 

---

app/views/helpers/awrsInputTypeText.scala.html

[AWRS-2147] - fix blank aria-labelledby within text input fields

[AWRS-2147] - fix blank aria-labelledby within text input fields

---

app/views/helpers/awrsProgressHelper.scala.html
public/stylesheets/custom.css

[AWRS-2191] - Fix progress header issue highighted by Wave

[AWRS-2191] - Fix progress header issue highighted by Wave

---

app/controllers/BusinessDetailsController.scala
app/controllers/BusinessNameChangeController.scala
app/forms/BusinessDetailsForm.scala
app/models/BusinessDetailModels.scala
app/services/ApplicationService.scala
app/services/DataCacheKeys.scala
app/services/IndexService.scala
app/services/KeyStoreService.scala
app/services/Save4LaterService.scala
app/views/awrs_business_details.scala.html
app/views/awrs_group_representative_change_confirm.scala.html
app/views/helpers/awrsInputTypeText.scala.html
app/views/helpers/awrsProgressHelper.scala.html
app/views/view_application/subviews/subview_business_contacts.scala.html
app/views/view_application/subviews/subview_core.scala.html
conf/app.routes
conf/messages
public/stylesheets/custom.css
test/controllers/BusinessDetailsControllerTest.scala
test/controllers/BusinessNameChangeControllerTest.scala
test/forms/BusinessDetailsFormTest.scala
test/services/ApplicationServiceTest.scala
test/services/mocks/MockKeyStoreService.scala
test/utils/TestUtil.scala
test/views/BusinessDetailsViewTest.scala

Reverts hmrc/awrs-frontend#100

Revert "Revert "Awrs 2179 2183""

---

app/controllers/BusinessNameChangeController.scala

[AWRS-2179-2183] fix trading name amend when changing business name

[AWRS-2179-2183] fix trading name amend when changing business name

---

app/views/awrs_index.scala.html
app/views/helpers/awrsPrintLink.scala.html
app/views/view_application/awrs_view_application_core.scala.html
public/javascripts/awrs.js

[AWRS-2193] - Registration - Google Analytics - Tracking for 'Print' from Application Summary

[AWRS-2193] - Registration - Google Analytics - Tracking for 'Print' 

---

app/services/IndexService.scala
app/services/helper/BusinessDetailsAndContactsComparator.scala

[AWRS-2204] - Incorrect status shown after edit of Business Name

[AWRS-2204] - Incorrect status shown after edit of Business Name

---

app/views/awrs_index.scala.html
app/views/helpers/awrsPrintLink.scala.html
app/views/view_application/awrs_view_application_core.scala.html
public/javascripts/awrs.js

[AWRS-2193] - add data-journey-click attribute for GA tracking

[AWRS-2193] - add data-journey-click attribute for GA tracking

---

conf/application.conf

fix security policy

---

app/controllers/AddressLookupController.scala
test/controllers/AddressLookupControllerTest.scala

Reverts hmrc/awrs-frontend#123

Revert "Ddcnls 2267"

---

app/config/ApplicationConfig.scala
app/views/govuk_wrapper.scala.html

DDCNLS-3306: Removed beta banner

DDCNLS-3306: Removed beta banner

---

app/forms/prevalidation/PrevalidationAPI.scala
app/forms/prevalidation/package.scala
app/forms/validation/util/ErrorMessageAPI.scala
app/forms/validation/util/NamedMappingAndUtil.scala
app/services/helper/BusinessDetailsAndContactsComparator.scala
app/utils/AwrsValidator.scala
scalastyle-config.xml
test/forms/test/util/FormValidationTestAPI.scala
test/forms/test/util/NamedUnitTests.scala
test/services/ApplicationServiceTest.scala
test/utils/TestConstants.scala

DDCNLS-3105

---

conf/messages

@KeertiGottamHMRC - I have now refactored the messages file, again. The unit tests are okay but it just needs acceptance tests run on it.

DDCNLS-2873 Tidy and refactoring messages file

---

conf/messages

messages updated

---

conf/messages

Reverts hmrc/awrs-frontend#151

Revert "messages updated"

---

conf/messages

Reverts hmrc/awrs-frontend#149

Revert "DDCNLS-2873 Tidy and refactoring messages file"

---

app/connectors/AWRSConnector.scala
app/connectors/AWRSNotificationConnector.scala
test/connectors/AWRSConnectorSpec.scala

This reverts commit 2b2c29c248554eceb0038f6a0eb5b383b0dc79ea.

Revert "Error messages amended to trace in staging"

---

conf/application.conf
project/FrontendBuild.scala
test/controllers/ApplicationControllerTest.scala

**Bug fix **
update to use new feedback url

DL-1792: update to use new feedback url

---

app/connectors/EmailVerificationConnector.scala
test/connectors/EmailVerificationConnectorTest.scala

**Bug fix**
Fixing issue with user emails being leaked in logs because they are part of the url. Moved to a JSON body.

DL-1901 corrected usage of email verification to prevent leaks in logs

---

project/FrontendBuild.scala

**Bug fix**
Changing hmrctest version as app fails to build on Jenkins, and investigations indicate the issue may lie with this dependency.

DL-1834: roll back hmrctest version

---

project/Microservice.scala

On platops team's suggestion, have set forkInTest to true, to see if the app will build in Jenkins.

DL-1834: set fork in test to true

---

test/connectors/AWRSNotificationConnectorSpec.scala

DL-1834 - Fix for failing jenkins test

---

project/FrontendBuild.scala
project/plugins.sbt
public/javascripts/postcodeLookup.js

DL-2011 
Bug FIx
Fixed bug so that address isn't pre-selected when looking up postcode. Unit and integration tests passed. Local chrome acceptance test passed but wasn't able to run other acceptance tests on my machine. 
Not sure whether or not to add a test for making sure that no address is pre selected when looking up postcode.
Also was not able to update http-caching-client library as it broke the unit test.

DL-2011 Fixed Bug and updated dependencies

---

app/controllers/IndexController.scala
app/controllers/WithdrawalController.scala
app/controllers/auth/AuthFunctionality.scala
app/controllers/util/UnSubmittedBannerUtil.scala
app/services/ApplicationService.scala
app/services/KeyStoreService.scala
app/services/Save4LaterService.scala
app/utils/AccountUtils.scala
test/utils/AccountUtilsTest.scala

**Bug fix**
Re-implementing the functionality from before the auth upgrade.
See: https://github.com/hmrc/awrs-frontend/blob/f5eb6f50b43bb08eabec6b1447d864b92e3f852a/app/utils/AccountUtils.scala#L26-L33
- []  I've executed the acceptance test pack locally to ensure there are no functional regressions
- []  I've run a dependency check to ensure all dependencies are up to date

DL-2020: Fixed getUtr bug.

---

conf/application.conf

DL-2214- Update Google Analytics config to be determined in app-config
**Maintenance**
Existing config was being determined at repo level and not consistent with being able to test in QA and STAGING which have since been set up. Resetting config to standard implementation

DL-2214 amending config for GA

---

app/connectors/TaxEnrolmentsConnector.scala

**Log extension**
Expanded the log message for retries for ES8 onto to EACD

DL-2462 Expanded retry EACD log

---

app/connectors/AWRSConnector.scala
app/controllers/ApplicationDeclarationController.scala
app/models/ConnectionModels.scala
app/services/ApplicationService.scala
app/services/EnrolService.scala
test/connectors/AWRSConnectorSpec.scala
test/connectors/mock/MockAWRSConnector.scala
test/controllers/ApplicationDeclarationControllerTest.scala
test/services/ApplicationServiceTest.scala
test/services/EnrolServiceTest.scala

**Bug fix**
Self heal logic fix

DL-2462 - Self heal logic fix

---

app/controllers/ApplicationDeclarationController.scala
test/controllers/ApplicationDeclarationControllerTest.scala

**Redirect change**
* Changed redirect route in self heal cases

DL-2462 Changed self-heal redirect route

---

app/connectors/AWRSConnector.scala
it/uk/gov/hmrc/helpers/controllers/HomeControllerSpec.scala

**Bug fix**
* Fixed etmp-check url for AWRS-BE.

etmp-check-fix Fixed AWRS-BE url for etmp check route

---

project/FrontendBuild.scala
project/Microservice.scala
project/plugins.sbt

DL-2714
**Maintenance**
Updated Dependencies, plugins and scala version 

DL-2714 Upgrade Dependencies and Plugins

---

project/plugins.sbt

DL-2714
**Maintenance** 
Adding scalastyle plugin which broke in Jenkins build

DL-2714 adding latest scalastyle plugin

---

app/controllers/ApplicationStatusController.scala
app/services/apis/AwrsAPI5.scala
app/services/helper/BusinessDetailsAndContactsComparator.scala
conf/logback.xml
test/controllers/ApplicationStatusControllerTest.scala
test/controllers/BusinessTypeControllerTest.scala
test/services/apis/AwrsAPI5Test.scala

**Bug fix**
* Added bug fix for cases where cached API5 data couldn't be loaded to the new format - this fix converts those cases.

DL-2790 Bug fix for newAwBusiness

---

app/connectors/AWRSConnector.scala
app/services/CheckEtmpService.scala
it/uk/gov/hmrc/helpers/application/IntegrationApplication.scala
it/uk/gov/hmrc/helpers/controllers/HomeControllerSpec.scala
test/connectors/AWRSConnectorSpec.scala
test/controllers/HomeControllerTest.scala
test/services/CheckEtmpServiceTest.scala

**Bug fix**
* Self-heal checks from users arriving from business-customer should now perform ES8 on success

DL-2783 ES8 for self-heal

---

app/connectors/AWRSConnector.scala
app/controllers/BusinessTypeController.scala
app/controllers/HomeController.scala
app/models/EtmpSupportModels.scala
app/services/CheckEtmpService.scala
it/resources/api5/llpit.json
it/uk/gov/hmrc/helpers/JsonUtil.scala
it/uk/gov/hmrc/helpers/application/S4LStub.scala
it/uk/gov/hmrc/helpers/controllers/BusinessTypeControllerISpec.scala
it/uk/gov/hmrc/helpers/controllers/HomeControllerISpec.scala
project/FrontendBuild.scala
test/connectors/AWRSConnectorSpec.scala
test/controllers/BusinessTypeControllerTest.scala
test/controllers/HomeControllerTest.scala
test/services/CheckEtmpServiceTest.scala
test/views/BusinessTypeViewTest.scala

**Logic changes**
* Relocated self-heal regime logic checks on awrs-frontend
* This changes the required data and allows users, given they've provided a business type, to have the self-heal mechanism activate and bring them to the state they should be at

DL-2783 Relocated self-heal regime check logic

---

app/connectors/AWRSConnector.scala
app/utils/AccountUtils.scala
it/uk/gov/hmrc/helpers/controllers/BusinessTypeControllerISpec.scala
project/FrontendBuild.scala
project/plugins.sbt
test/connectors/AWRSConnectorSpec.scala
test/connectors/AWRSNotificationConnectorSpec.scala
test/utils/AccountUtilsTest.scala

**Altered routes**
* Altered routes to the AWRS backend to use the revised routes which don't send unused data

DL-2215 Altered AWRS frontend to use new routes

---

project/FrontendBuild.scala
test/services/ApplicationServiceTest.scala

**Test change**
* Added a minor test change to attempt to fix intermittent build failures that sometimes occur
Reviewee (Paul Anderson)

DL-2801 Minor test change for intermittent build failures

---

app/views/awrs_trading_activity.scala.html
public/javascripts/awrs.js

**Bug fix**
* Fixed bugs with the progressive disclosure involving the export alcohol question on the trading activity page.

DL-2288 Fixed progressive disclosure function on trading activity page

---

app/controllers/BusinessRegistrationDetailsController.scala
app/controllers/ViewApplicationController.scala
app/views/awrs_already_starting_trading.scala.html
app/views/awrs_business_registration_details.scala.html
app/views/awrs_legislation_date.scala.html
app/views/awrs_trading_date.scala.html
app/views/helpers/backLink.scala.html
test/controllers/BackButtonFunctionalityTest.scala
test/controllers/BusinessRegistrationDetailsControllerTest.scala
test/views/BusinessRegistrationDetailsViewTest.scala

**Bug fix**
* Updated back links to not use browser back, preventing document expired issues.

DL-2715 Updated back links to not use browser back

---

app/views/awrs_already_starting_trading.scala.html
app/views/awrs_business_directors.scala.html
app/views/awrs_legislation_date.scala.html
app/views/awrs_products.scala.html
app/views/awrs_trading_date.scala.html
app/views/awrs_trading_name.scala.html
app/views/govuk_wrapper.scala.html
app/views/helpers/errorSummaryTemplate.scala.html
conf/messages
project/AppDependencies.scala

**Bug fix**
Fixed a few cases of WAVE failing with ARIA reports.

DL-3307 Accessibility fixes

---

app/views/awrs_additional_premises.scala.html
app/views/awrs_business_contacts.scala.html
app/views/awrs_business_registration_details.scala.html
app/views/awrs_group_member.scala.html
app/views/awrs_index.scala.html
app/views/awrs_partner_member_details.scala.html
app/views/awrs_principal_place_of_business.scala.html
app/views/awrs_supplier_addresses.scala.html
app/views/helpers/awrsInputTypeGroupCheckbox.scala.html
app/views/helpers/awrsInputTypeRadioGroup.scala.html
app/views/helpers/awrsInputTypeText.scala.html
app/views/helpers/awrsPrintFriendlyWrapper.scala.html
app/views/includes/awrs_main.scala.html
public/javascripts/awrs.js
public/javascripts/details.polyfill.js

**Bug fix ** 
Fixes in response to accessibility issues identified by the validator
Fixed h2/h3 issue
Fixed issue with duplicate IDs
Fixed issue with some  divs wrapping fieldset content
Removed aria-role radiogroup from fieldset.
Corrected aria-described by on additional address form
Reviewee (Andy)

DL-3270 fix accessibility validator issues

---

app/views/helpers/awrsAnswerStatusDecision.scala.html
conf/messages
test/views/ApplicationStatusViewTest.scala

**Bug fix**
* Fixed broken message link from progressive disclosure on contesting a decision.

DL-2207 Fixed missing message link from progressive disclosure on status

---

app/config/ApplicationConfig.scala
conf/application.conf
project/AppDependencies.scala

**Bug fix**
* Fixed local signout redirecting to a service not part of the AWRS profile

DL-3336 Fixed local signout

---

app/config/ApplicationConfig.scala
conf/application.conf

**Bug fix** (delete as appropriate)
Address 404 reporting from index page where contact frontend link was being reported in kibana logs

contactFix amend url contruct for contact host

---

app/controllers/ApplicationController.scala
project/AppDependencies.scala
project/build.properties
project/plugins.sbt

DL-3381 AWRS Logout to Feedback Page fix
**Bug fix**
Links with PR for Business Customer Frontend DL-3381
When a user logs out of AWRS they should be redirected to the feedback page once this change goes in with the Business Customer Frontend PR.
Reviewee (Iyke)

DL-3381 AWRS Logout to Feedback Page fix

---

app/config/ErrorHandler.scala
conf/messages
test/controllers/EmailVerificationControllerTest.scala
test/controllers/WithdrawalControllerTest.scala

DL-3383: Generic error update
New feature
DL-3383: Generic error update
Reviewee (Nadin)
Reviewer (Iyke)

DL-3383: Generic error update

---

app/connectors/AWRSConnector.scala

awrsInfoLogFix
Amend output of json to debug level
Reviewee (Paul Anderson)

awrsInfoLogFix amend to debug output

---

test/controllers/DeRegistrationControllerTest.scala

DL-3660 Fixed race condition on unit test

---

conf/application-json-logger.xml
conf/logback-test.xml

**Bug fix**
* Updated logger config for awrs-frontend

DL-4179 Updated logger config

---

build.sbt
project/AppDependencies.scala
project/plugins.sbt

updatePlugins
**Bug fix** 
Removing sbt-artifactory plugin as seems to be causing issues in Jenkins build
Update other dependency and plugins at the same time

updatePlugins dependency and plugin updates

---

public/javascripts/postcodeLookup.js

DL-4208: Fixed postcode lookup javascript bug
I've pushed a branch up with uncommented AT tests so you can review this. https://github.com/hmrc/awrs-acceptance-tests/compare/DL-3189
Going to put DL-3189 up for review following Marjan's change.

DL-4208: Fixed postcode lookup javascript bug

---

build.sbt
project/AppDependencies.scala
test/controllers/WithdrawalControllerTest.scala

AWRS - Unit Test coverage for AWRS-1329 API8 Withdrawal feature
**New feature** 
Added additional tests for Withdraw Registration so that all options on the page are tested.
Reviewee (Iyke)

DL-3206 Withdraw Registration Tests

---

app/forms/TradingDateForm.scala

Running scala format on failing file

DL-4449 scalaformat on TradingDateForm

---

app/forms/DeRegistrationForm.scala
project/AppDependencies.scala
project/plugins.sbt
test/controllers/DeRegistrationControllerTest.scala

DL-3207: Added unit tests for dereg reasons

DL-3207: Added unit tests for dereg reasons

---

app/config/ApplicationConfig.scala
app/controllers/auth/AuthFunctionality.scala
conf/application.conf
project/AppDependencies.scala

DL-4814 Switch from CA Frontend to BAS Gateway
Dependency Update
Goes with:
https://github.com/hmrc/service-manager-config/pull/3223
https://github.com/hmrc/app-config-base/pull/4886
Reviewee (Iyke)

DL-4814 Switch from CA Frontend to BAS Gateway

---

test/views/IndexViewTest.scala
test/views/TradingNameViewTest.scala

Added a back link check in TradingNameViewTest and a username check in IndexViewTest

DL-3215: Added back link and loggedInUserName check

---

test/views/GroupMembersViewTest.scala

DL-3212: Added UTR and CRN text check to GroupMembersViewTest

DL-3212: Added UTR and CRN text check

---

test/controllers/BusinessNameChangeControllerTest.scala
test/views/IndexViewTest.scala

**Unit tests**
* Added additional unit test coverage transferred from group ltd ATs.

DL-3227 Unit test coverage from Group Ltd ATs

---

app/config/ApplicationConfig.scala
app/views/govuk_wrapper.scala.html
conf/application.conf
project/AppDependencies.scala

DL-5033: Add cookie consent/switch off GA

DL-5033: Add cookie consent/switch off GA

---

app/connectors/AddressLookupConnector.scala
project/AppDependencies.scala
project/plugins.sbt

**Uplift**
* Uplift awrs-frontend's address-lookup endpoint to use one that won't be deprecated in the future.

DL-5254 Uplift address-lookup endpoint

---

build.sbt
project/plugins.sbt

**Dependency removal**
* Remove bintray dependency

DL-5403 Bintray dependency update

---

app/connectors/AWRSConnector.scala
app/connectors/AWRSNotificationConnector.scala
app/connectors/AddressLookupConnector.scala
app/connectors/BusinessMatchingConnector.scala
app/connectors/EmailVerificationConnector.scala
app/connectors/RawResponseReads.scala
app/connectors/TaxEnrolmentsConnector.scala
build.sbt
project/AppDependencies.scala
project/build.properties
project/plugins.sbt
test/connectors/AWRSConnectorSpec.scala
test/connectors/AWRSNotificationConnectorSpec.scala

**Bootstrap update**
* Updated awrs-frontend to the latest frontend play-bootstrap.

DL-5284 Bootstrap update

---

app/views/awrs_business_contacts.scala.html
test/utils/TestUtil.scala
test/views/BusinessContactsViewTest.scala

DL-6136 Fix address related bug.

---

app/views/awrs_business_directors.scala.html
app/views/awrs_group_member.scala.html
app/views/view_application/subviews/contents/content_director.scala.html
app/views/view_application/subviews/contents/content_partner_detail.scala.html
app/views/view_application/subviews/subview_business_details.scala.html
conf/messages
project/AppDependencies.scala
project/plugins.sbt
test/views/view_application/ViewApplicationTest.scala

DL-7848: Removed duplicate trading field and updated label
Updated dependencies 
Updated plugins
Removed unused message

DL-7848: Removed duplicate trading field and updated label

---

app/views/awrs_application_confirmation.scala.html
app/views/awrs_application_status.scala.html
app/views/awrs_application_update_confirmation.scala.html
app/views/awrs_email_verification_error.scala.html
app/views/awrs_index.scala.html
app/views/helpers/awrsPrintLink.scala.html
app/views/helpers/returnToIndex.scala.html
app/views/subtemplates/application_status/approved_info.scala.html
app/views/unauthorised.scala.html
app/views/view_application/helpers/add_link_helper.scala.html
app/views/view_application/helpers/add_none_table_link_helper.scala.html
app/views/view_application/helpers/table_row.scala.html
app/views/view_application/subviews/subview_core.scala.html
public/stylesheets/custom.css

DL-7849 Fix font sizing on govuk links

---

app/views/awrs_application_update_confirmation.scala.html

DL-9458: Fixed formatting for update-confirmation

DL-9458: Fixed formatting for update-confirmation

---

app/controllers/BusinessDirectorsController.scala
test/controllers/BusinessDirectorsControllerTest.scala

**Bug fix** (delete as appropriate)
Fix for cleansing of answers for irrelevant questions relating to directors, including extra unit tests.

DL 9722 Cleansing data of irrelevant questions

---

app/connectors/AWRSConnector.scala
app/controllers/BusinessTypeController.scala
app/controllers/HomeController.scala
app/controllers/WrongAccountController.scala
app/controllers/auth/AuthFunctionality.scala
app/models/AwrsUsersModel.scala
app/services/CheckEtmpService.scala
app/views/awrs_account_exists.scala.html
conf/app.routes
conf/messages
it/uk/gov/hmrc/helpers/controllers/HomeControllerISpec.scala
test/connectors/AWRSConnectorSpec.scala
test/controllers/ApplicationStatusControllerTest.scala
test/controllers/BusinessTypeControllerTest.scala
test/controllers/HomeControllerTest.scala
test/services/CheckEtmpServiceTest.scala
test/services/apis/AwrsAPI10Test.scala
test/utils/TestUtil.scala

Dl 9708 - Wrong account page and logic.

---

app/connectors/AWRSConnector.scala
app/services/CheckEtmpService.scala
test/connectors/AWRSConnectorSpec.scala

DL-10588 - fix to accomodate no regime number scenario

---

app/assets/stylesheets/custom.css
app/views/helpers/awrsInputTypeText.scala.html
app/views/helpers/fieldErrorHelper.scala.html
app/views/view_application/helpers/address_helper.scala.html
app/views/view_application/subviews/contents/content_additional_premises.scala.html
app/views/view_application/subviews/contents/content_partner_detail.scala.html
app/views/view_application/subviews/subview_additional_premises.scala.html

To improve accessibility and remove accessibility fails.

Updating classes, and markup and adding Error prefix to postcode fields

---

app/assets/stylesheets/custom.css
app/views/view_application/subviews/contents/content_partner_detail.scala.html
test/views/view_application/ViewApplicationTest.scala

**Bug fix**
The headings on the business partners section were wrapping incorrectly - this fixes that issue.
Reviewee: Stuart
Reviewer (Paul)

DL 10950: AWRS - Business Partner (Edit) summary list wrap small devices

---

app/config/wiring.scala
it/uk/gov/hmrc/helpers/application/IntegrationApplication.scala

correct config keys in the wiring file

---

app/views/view_application/awrs_view_application_core.scala.html
app/views/view_application/subviews/subview_core.scala.html
test/views/view_application/ViewApplicationTest.scala

**Bug fix**
Removed extra back link and made IDs unique.

DL 11816 - View Application view changes

---

test/views/view_application/ViewApplicationTest.scala

**Bug fix**
Removal of line from ViewApplicationTest.

DL-11816 Removal of extra line in ViewApplicationTest

---

app/controllers/HomeController.scala

Added logging to initial fetch of BC details

---

app/views/view_application/subviews/contents/content_partner_detail.scala.html

Empty h2 was breaking accessibility tests and failing accessibility.

Remove empty h2

---

project/AppDependencies.scala

update http-caching-client version

---

app/controllers/ApplicationController.scala
app/views/layout.scala.html
app/views/main.scala.html
app/views/timed_out.scala.html
conf/messages
test/controllers/ApplicationControllerTest.scala
test/views/TimedOutViewTest.scala
test/views/ViewTestFixture.scala

DL-14542: Timeout dialog initiated twice and other issues (AA)

---

conf/app.routes
test/views/ViewTestFixture.scala

DL-14542: updates for redirect from business customer frontend

---

app/views/view_application/awrs_view_application.scala.html
app/views/view_application/subviews/subview_core.scala.html
test/controllers/ViewApplicationControllerTest.scala

**Bug fix ** (delete as appropriate)
Removed extra backlink from subview

Removing extra back link

---

app/assets/stylesheets/custom.css
app/views/main.scala.html

DL-14502: changes css to allow spaces

---

app/config/ApplicationConfig.scala
conf/application.conf
test/FeatureFlagSpec.scala

added feature flag for enrolment journey and unit test

---

project/AppDependencies.scala

DL-15572 : Rolled Back "play-frontend-hmrc-play-30"

---

app/utils/AccountUtils.scala
test/connectors/mock/MockAuthConnector.scala
test/controllers/ApplicationDeclarationControllerTest.scala
test/controllers/BusinessTypeControllerTest.scala
test/controllers/DeRegistrationControllerTest.scala
test/controllers/HomeControllerTest.scala
test/controllers/TradingDateControllerTest.scala
test/utils/AccountUtilsTest.scala

Fixing tests

---

app/controllers/AwrsUrnKickoutController.scala
test/controllers/AwrsUrnKickoutControllerTest.scala

DL-15651 : Added btaAuthorisedAction to Kickout page & Updated Test

DL-15651 : Added btaAuthorisedAction to Kickout page & Updated Test

---

app/assets/javascript/postcodeLookup.js
project/AppDependencies.scala
project/plugins.sbt

DL-15572 : Changed postcodeLookup.js and updated  "uk.gov.hmrc"    %% "play-frontend-hmrc-play-30" to 11.11.0

DL-15572 : Changed postcodeLookup.js

---

app/config/ApplicationConfig.scala
app/controllers/ApplicationController.scala

Fixing signout url

---

app/forms/reenrolment/RegisteredPostcodeForm.scala
conf/messages
test/forms/reenrolment/RegisteredPostcodeFormTest.scala

Updating the postcode error message for Re-enrolment

---

app/forms/reenrolment/RegisteredUrnForm.scala
app/forms/reenrolment/RegisteredUtrForm.scala
conf/messages
test/forms/reenrolment/RegisteredUrnFormTest.scala
test/forms/reenrolment/RegisteredUtrFormTest.scala

DL-16342 and DL-16343 Replacing all URN and UTR errors with a generic error

---

app/controllers/HaveYouRegisteredController.scala
test/controllers/HaveYouRegisteredControllerTest.scala

DL-16341: redirection to business customer

---

test/controllers/ApplicationDeclarationControllerTest.scala
test/controllers/ApplicationStatusControllerTest.scala

DL-16316: Fixing flaky build

---

app/controllers/HaveYouRegisteredController.scala
project/AppDependencies.scala

The controller in business-customer contains authentication, hence why it is omitted in this controller.
DL-16511

DL-16511: Created unconditional redirect to controller in business-customer

---

app/views/main.scala.html

DL-13561: added region for logged in user
